version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dejeloper
      POSTGRES_PASSWORD: dejeloper123**
      POSTGRES_DB: opplanner_db
    ports:
      - 5499:5432
